### ISSUE TITLE
Issue while accessing first lab

### ISSUE THREAD

**Issue by AmirSoyelAhmed-hub** [shannonlindsay/Data-AI-Dev#1]
[#](url) Lab Name: Create a composite model
### Step: 04

Issue Type: blocking

Description of issue: Saving starter report throws error

Repro steps (please include screenshot if applicable):

1. Open starter report
1. Prompt database connection press save.
1. See the error

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/53456220/165026213-3dc2cef1-9d25-41b8-9557-35dde4b6515f.png">

**Comment by shannonlindsay** [comment]
Hi team - here's a workaround for this issue.

1. When you see the error message Amir noted above, select **Close**

2. On the home tab of the ribbon, select **Transform data** to open the Power Query editor
![image](https://user-images.githubusercontent.com/77289548/165131144-8c6b1eeb-a275-4d18-878b-f84081745bac.png)

3. Select the Order Date query and **Edit Permission**

<img width="500" alt="image" src="https://user-images.githubusercontent.com/77289548/165131335-8fd467d9-e05a-4a50-b018-69c373e298c5.png">

4. Select **Run**, and then select **Edit Credentials** from the warning at the top of the screen

5. Select **Okay** in the Encryption support popup window. Your query should now load.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/77289548/165131679-9fb156bb-3a6e-4902-8186-651c31c4d95f.png">

6. Step through each of the queries to ensure they all load, and then **Close and apply** - now you should be able to start the lab!

<img width="291" alt="image" src="https://user-images.githubusercontent.com/77289548/165131907-85d45ec5-c326-404a-92a2-5be7b9d3d2a9.png">

**Comment by AmirSoyelAhmed-hub** [comment]
Thank you @shannonlindsay, the workaround worked for me.

**Comment by shannonlindsay** [comment]
@AmirSoyelAhmed-hub - to get around the connection issues I saved the file as a .pbit (and updated the instructions). Learners will have to enter the database credentials, but it avoids any error messages. I will close the issue once it's confirmed this solution works properly! Thanks for raising this.

**Comment by AmirSoyelAhmed-hub** [comment]
Thank you @shannonlindsay.
