### ISSUE TITLE
DaxStudio Installable isn't available in lab files

### ISSUE THREAD

**Issue by strugdt** [shannonlindsay/Data-AI-Dev#10]
# Lab Name: Use tools to optimize Power BI performance
### Step: 01

Issue Type: blocking

Description of issue
D:\DP500\Software directory isn't available.

**Comment by shannonlindsay** [comment]
Thanks for the heads up on this. I need to update the instructions - students will need to download from: https://daxstudio.org/downloads/

**Comment by shannonlindsay** [comment]
This has been updated.
