### ISSUE TITLE
Add step - Native Database query

### ISSUE THREAD

**Issue by strugdt** [shannonlindsay/Data-AI-Dev#11]
# Lab Name: Improve query performance with dual storage mode
### Step: 04

Issue Type: non-blocking

Description of issue

After completing step 04, before report opens Students might get a pop as shown below. Can we add another step to let students know about this to avoid unnecessary questions - 

![image](https://user-images.githubusercontent.com/16652407/166060245-abad7f79-95a3-41f0-be10-65d170a37974.png)

**Comment by shannonlindsay** [comment]
yep! I'll add that - thank you!
