### ISSUE TITLE
Unable to find lab credentials

### ISSUE THREAD

**Issue by AmirSoyelAhmed-hub** [shannonlindsay/Data-AI-Dev#12]
# Lab Name: Create reusable Power BI artifacts
### Step: 00

Issue Type: blocking

Description of issue Unable to find login credentials to login to the power bi service from the resources section of lab

Repro steps (please include screenshot if applicable):

1.
1.
1.

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/53456220/166137897-8be2d7d8-119e-4525-af6c-bd16e4425af9.png">

**Comment by AmirSoyelAhmed-hub** [comment]
@shannonlindsay ..The same is true for lab "Enforce model security" .

**Comment by sherzyang** [comment]
@AmirSoyelAhmed-hub, if you click on the "Resources" tab in the VM you will see a username (email) and password. Those seem to be right credentials for logging in. 

![support-1](https://user-images.githubusercontent.com/19577448/166158764-bfb3b376-7087-415d-8ba7-fa48ae63b473.png)

**Comment by shannonlindsay** [comment]
@AmirSoyelAhmed-hub - does Sherry's screenshot solve your problem?  let us know here!

**Comment by AmirSoyelAhmed-hub** [comment]
Hi @sherzyang and @shannonlindsay, 
Apologies I was unable to respond earlier. I was unable to find the credentials in the lab profile.
<img width="631" alt="image" src="https://user-images.githubusercontent.com/53456220/166420452-98447e43-7751-49fc-b085-24e69a16ef0f.png">


This is all I could find:
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/53456220/166420531-8c72f82b-0885-4557-93f9-dd7d14f73e3c.png">


Thanks and Regards,
Amir Soyel Ahmed

**Comment by AmirSoyelAhmed-hub** [comment]
Using the credentials from other VMs show this error.
<img width="710" alt="image" src="https://user-images.githubusercontent.com/53456220/166422244-0f83685a-ae4e-4b49-81df-361be5712e2b.png">
