### ISSUE TITLE
Missing Synapse folder in DP000

### ISSUE THREAD

**Issue by sherzyang** [shannonlindsay/Data-AI-Dev#13]
# Lab Name: Analyze Data in a Data lake with SQL 
### Step: 06

Issue Type: **non-blocking**

Description of issue: Drilling down, the DP000-xxxxx resource group contains a synapse workspace with a Data-->Linked-->files container with one Sales folder. It doesn't seem to contain a Synapse container. However, checking the DP500-xxxx resource group's synapse workspace-->Data-->Linked-->files container there is a Synapse folder, but no Sales folder.  

Repro steps (please include screenshot if applicable):
From the DP000-xxxx resource group: 
![Snag_5cd92cb1](https://user-images.githubusercontent.com/19577448/166156882-1c195da3-bd84-449c-9468-dcf1b0f05fb8.png)

From the DP500-xxxx resource group:
![Snag_5cd958f1](https://user-images.githubusercontent.com/19577448/166156890-e1b5fab6-0980-42d9-86b5-cb26a26e290b.png)

**Comment by shannonlindsay** [comment]
Lab profile: 111889

Need to revisit this - talk to Skillable.
