### ISSUE TITLE
Add instruction to delete RG after lab

### ISSUE THREAD

**Issue by sherzyang** [shannonlindsay/Data-AI-Dev#15]
# Lab Name: Analyze data in a data lake with SQL 
### Step: 03

Issue Type: **non-blocking**

Description of issue: Suggesting that it could also help students if they deleted both the DP500-xxxx and DP000-xxxx resource groups. 

Repro steps: 
1.  If students only delete DP500-xxxx RG they will have a DP000-xxxx RG remaining. If they go right to the _data lake with Spark_ lab, they will create another DP000-xxxx RG and it might be confusing; as only the Spark's lab setup DP000-xxxx script creates a spark pool.

**Comment by sherzyang** [comment]
**Lab Name: Analyze data in a data lake with Spark**
**Task: Delete Azure resources 
Step: 03** 

Just the same suggestion as above for the instructions at the end of this lab.

**Comment by shannonlindsay** [comment]
I think I understand :) This issue is being caused by the fact that we're both automatically and manually running the scripts, so two RGs are being created. If I am understanding the issue correctly this will be solved in the classroom environment. Does this track with you @sherzyang?
