### ISSUE TITLE
Suggestion to add note for if repo is already cloned

### ISSUE THREAD

**Issue by sherzyang** [shannonlindsay/Data-AI-Dev#16]
# Lab Name: Create a star schema model
### Step: 04

Issue Type: **non-blocking**

Description of issue: If students go from one lab to the next, they may not know what to do when they get an error that the repo cannot be cloned again under the same name. 

Repro steps (please include screenshot if applicable):

1. I've gotten bugs for AI900 labs where each lab asks students to clone the repo, but if a student does multiple labs, they get a warning that the repo is already cloned and cannot be cloned again under the same name. I've just added notes like the one in the image below. Just a suggestion! 

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/19577448/166158577-72d4a020-e0db-4117-9dc7-9db78a38af16.png)

**Comment by shannonlindsay** [comment]
Thanks Sherry! I added this note :)
