### ISSUE TITLE
Not sure how to get to Synapse Studio

### ISSUE THREAD

**Issue by sherzyang** [shannonlindsay/Data-AI-Dev#18]
# Lab Name: Create a star schema model
### Step: 01

Issue Type: **blocking**

Description of issue: I am not quite sure how to complete step 1 after the previous section's steps. This may not be a universal experience. I am not sure if I missed a step elsewhere. 

Repro steps (please include screenshot if applicable):

1. After I resume the SQL pool, I am on this pane [EDIT: Now I see I could have just clicked on the "Open in Synapse Studio" button on the ribbon]: 
![support-2](https://user-images.githubusercontent.com/19577448/166160311-9387d028-1140-46ca-99e9-f140d2fc9175.png)

2. I'm asked to log into the Synapse Studio. I tried using the LODS login info but it did not work. I was able to log in using my personal account. However, unfortunately I wasn't able to connect to my existing workspace name: 
![support-3](https://user-images.githubusercontent.com/19577448/166160554-e6442346-7944-4989-912f-7cdb2c123a2c.png)

**Comment by shannonlindsay** [comment]
Hi Sherry - thanks for this feedback. I added language to clear up how to get to Synapse Studio.

For the 2nd issue - you should be able to login using the LODS login info from the resources tab. Let's see who else receives this message and figure out how to fix it. I'm stumped at the moment.

**Comment by sherzyang** [comment]
Thanks @shannonlindsay! Ok this solved it, thanks!
