### ISSUE TITLE
Issue in changing width 

### ISSUE THREAD

**Issue by AmirSoyelAhmed-hub** [shannonlindsay/Data-AI-Dev#2]
# Lab Name: Create a paginated report
### Step: 15

Issue Type: non-blocking

Description of issue
Unable to change the report body width to 6in . After saving report, it reverts to original size
Repro steps (please include screenshot if applicable):

1.Click on Quantity textbox in the report body.
2.Select Body
3. Size - > Width 
4.  Make width as 6.
5. Click outside, it gets reverted back.

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/53456220/165050579-5488a535-0c5a-4c95-b7c7-f4eb1600e56b.png">

**Comment by shannonlindsay** [comment]
Thanks Amir - I'll take a look :)
