### ISSUE TITLE
Missing step in refreshing visuals in Performance analyzer

### ISSUE THREAD

**Issue by bpmoring** [shannonlindsay/Data-AI-Dev#20]
# Lab Name: Improve query performance with aggregations
### Step: 02

Issue Type: **non-blocking**

I found it helpful when in the Improve query performance with dual storage mode you included the step: In the Performance analyzer pane, select Clear and then have them refresh visuals.

![image](https://user-images.githubusercontent.com/87440652/166831119-c2588cd9-ef37-4cd2-9b1f-4f13706a9c3b.png)

**Comment by shannonlindsay** [comment]
Lab profile: 117782
