### ISSUE TITLE
Connect to Data Source credentials

### ISSUE THREAD

**Issue by sherzyang** [shannonlindsay/Data-AI-Dev#22]
# Lab Name: Create a dataflow
### Step: 05

Issue Type: **blocking**

Description of issue: Step 5 is marked as TODO. I think it should have the credentials to help the user Connect to Data Source. 

Repro steps (please include screenshot if applicable):

1. It looks like we need the Server, Username, and Password to connect. 
![support-4](https://user-images.githubusercontent.com/19577448/166851407-ca2e38ea-da25-4fb3-8960-1025cbb01597.png)

2. I found the Server name in the Dedicated SQL Pool's "Connection String" pane 
![Snag_6e25300a](https://user-images.githubusercontent.com/19577448/166853342-caa394eb-c5a5-49cd-a9f9-524f4521c2cb.png)

3. For Authentication Kind, I selected "log into organization" instead of "basic" and used the credentials provided by Skillable and was able to connect to data source.

4. Small add-on -- the following step 7 (as seen in the first screenshot above) goes directly to table selection. I suggest adding a few words "Select **sqldw**, then find the table"
![Snag_6e2b2455](https://user-images.githubusercontent.com/19577448/166853780-5d602829-6dbb-4105-9561-02a10cc0f0d1.png)

**Comment by sherzyang** [comment]
Minor "_TODO: Provide an image_" in same lab (Create a Dataflow)
![Snag_6e216cc8](https://user-images.githubusercontent.com/19577448/166853097-318c1314-b210-424d-acfa-eb0175d6aa33.png)

**Comment by shannonlindsay** [comment]
this feedback is so great - thank you! It's updated now :) Both pieces.
