### ISSUE TITLE
Bar chart different than expected

### ISSUE THREAD

**Issue by sherzyang** [shannonlindsay/Data-AI-Dev#23]
# Lab Name: Create a Dataflow
### Step: 4-6

Issue Type: **non-blocking**

Description of issue: After dragging the fields into the bar chart visual, my bar chart appears as one bar. I may have made a mistake somewhere upstream. 

Repro steps (please include screenshot if applicable):

1. After Steps 4 and 5, I noticed my bar chart didn't look like the bar chart in the screenshot in Step 6. However, I was able to complete all the steps.  

![Snag_6e3df5e6](https://user-images.githubusercontent.com/19577448/166855147-aa470d7c-05a7-4412-8f80-9991fbc2115a.png)

**Comment by shannonlindsay** [comment]
It looks like your month offset filter value is blank, which makes me think that the DAX for the month offset filter column wasn't quite right. Let me see if this is related to the other DAX issue that was mentioned :)

Lab profile: 111889
