### ISSUE TITLE
Stopping the SQL pool

### ISSUE THREAD

**Issue by sherzyang** [shannonlindsay/Data-AI-Dev#24]
# Lab Name: Creating a dataflow
### Step: 03

Issue Type: **non-blocking**

Description of issue: Not sure if we are able to stop the SQL pool, only pause it 

![Snag_6e3fe7f2](https://user-images.githubusercontent.com/19577448/166855269-52b1ef48-c1d0-4d34-95f9-3a12dbac8f90.png)

**Comment by shannonlindsay** [comment]
Good point - changed that language :)
