### ISSUE TITLE
Create calculation group header 

### ISSUE THREAD

**Issue by sherzyang** [shannonlindsay/Data-AI-Dev#25]
# Lab Name: Create a Paginated Report
### Step: 4

Issue Type: **non-blocking**

Description of issue: When I used the Sales Order Number: 51721, the report only has 1 page. I suggest just deleting Step 4 which asks students to explore pages 2 and 3, as those are not in the report to my knowledge for this sales order number. 

![Snag_6e732a13](https://user-images.githubusercontent.com/19577448/166859005-c16ae2d5-69bd-4f7d-83e2-4ff3e880d15d.png)

**Comment by sherzyang** [comment]
Minor issue about how to determine where the Paginated report lab ends. It looks like adding a header for "Create Calculation Group" would be helpful to separate it from the previous lab. However, it doesn't seem like this will be an issue when the labs are divided up.

**Comment by shannonlindsay** [comment]
Thank you! I added the title to the markdown file :)
