### ISSUE TITLE
Updating PowerBI - Minor

### ISSUE THREAD

**Issue by sherzyang** [shannonlindsay/Data-AI-Dev#26]
# Lab Name: Create a paginated report
### Step: 1-2

Issue Type: **non-blocking**

Description of issue: Would be helpful to add step about updating PowerBI if asked. 
![Snag_6e75f808](https://user-images.githubusercontent.com/19577448/166859241-12e5dcc1-5c5e-4daf-ac43-8f0753c6da54.png)

**Comment by shannonlindsay** [comment]
Ah yes - thank you! I added this in between steps 1 & 2.
