### ISSUE TITLE
Folder name - Minor

### ISSUE THREAD

**Issue by sherzyang** [shannonlindsay/Data-AI-Dev#27]
# Lab Name: Create a Paginated Report
### Step: 15

Issue Type: **non-blocking**

Description of issue: Just need to change path from DP100 to DP500
![Snag_6e77d880](https://user-images.githubusercontent.com/19577448/166859393-4b9fbad5-1c06-464c-91f5-13aec571fad4.png)

**Comment by shannonlindsay** [comment]
Thank you for catching this! It's fixed now :)
