### ISSUE TITLE
Missing modeling group in home ribbon

### ISSUE THREAD

**Issue by sherzyang** [shannonlindsay/Data-AI-Dev#28]
# Lab Name: Create reusable Power BI artifacts
### Step: 01

Issue Type: **blocking** 

Description of issue: The home ribbon doesn't seem to have the Modeling group.

![Snag_6e8a0769](https://user-images.githubusercontent.com/19577448/166860761-26ae0c24-035c-42f0-bbb4-f04f726e666a.png)

**Comment by shannonlindsay** [comment]
Lab profile 117782 (PBI)

**Comment by shannonlindsay** [comment]
Thanks Sherry - I added instructions to turn this on - it's still a preview feature but will be GA by the time of release.
