### ISSUE TITLE
Suggestion to add step 

### ISSUE THREAD

**Issue by sherzyang** [shannonlindsay/Data-AI-Dev#3]
# Lab Name: Create a composite model 
### Step: 5-6

Issue Type: **blocking** 

Description of issue: Step needed between the current steps 5 & 6 

Repro steps (please include screenshot if applicable):

1. After selecting load (Step #5), I am asked to select the connection before the encryption window appears (Step #6). I suggest adding a step: "On the Windows tab, select Use my current credentials and select Connect". 
![image](https://user-images.githubusercontent.com/19577448/165369996-9ecd03c8-ce42-4b05-bf0c-0837fb7bd657.png)

![image](https://user-images.githubusercontent.com/77289548/164813485-54e7cc1a-7784-40d7-bda7-4627acc6345a.png)

**Comment by shannonlindsay** [comment]
Thank you @sherzyang - this has been updated!
