### ISSUE TITLE
Warning while opening predeveloped report

### ISSUE THREAD

**Issue by AmirSoyelAhmed-hub** [shannonlindsay/Data-AI-Dev#4]
# Lab Name: Improve query performance with aggregations
### Step: 3

Issue Type: **non-blocking**

Description of issue: Warning option when opening predeveloped report

Repro steps (please include screenshot if applicable):

1. Opening report shows the following warning. 
<img width="602" alt="image" src="https://user-images.githubusercontent.com/53456220/165503871-8d14b40e-eb57-4486-b734-88de7b9e4757.png">

**Comment by shannonlindsay** [comment]
Thanks Amir - added this to the instructions under step 3.

**Comment by AmirSoyelAhmed-hub** [comment]
Thank you @shannonlindsay .
