### ISSUE TITLE
Make instructions more clearer

### ISSUE THREAD

**Issue by strugdt** [shannonlindsay/Data-AI-Dev#5]
# Lab Name: Create reusable Power BI artifacts 
### Step: 05

Issue Type: Non-blocking

Description of issue : Please make this instruction more clear. We could change it to "Enter the SQLServerInstance, SqlServerDatabase, and Culture **as provided below**. Select Load."

![image](https://user-images.githubusercontent.com/16652407/165584169-99561581-8b54-4a5d-b246-1fbf93aac881.png)

**Comment by shannonlindsay** [comment]
Thanks for the detailed feedback Deepanshu!
