### ISSUE TITLE
Clicking on TypeText doesn't paste in PowerShell

### ISSUE THREAD

**Issue by sherzyang** [shannonlindsay/Data-AI-Dev#6]
# Lab Name: Analyze Data Lake with SQL
### Step: 4+5

Issue Type: **non-blocking**

Description of issue: Clicking on TypeText with the cursor in PowerShell seems to have the same effect as trying to do Ctrl+V. 

Repro steps (please include screenshot if applicable):

1. Put cursor in PowerShell, and click "T" next to TypeText. 
1. The result is "^V" instead of the actual text. I suggest just removing the TypeText around the commands (ie. remove +++_+++) and asking the student to copy and right click, paste.  

![image](https://user-images.githubusercontent.com/19577448/165849044-8fd066b3-7b53-43f7-b40f-7bc0598452c0.png)

**Comment by shannonlindsay** [comment]
Thanks Sherry!
