### ISSUE TITLE
Add a comment for "User Access Control PopUp"

### ISSUE THREAD

**Issue by strugdt** [shannonlindsay/Data-AI-Dev#7]
# Lab Name: Create a composite model
### Step: 09

Issue Type: Non-blocking

Description of issue : When you click at "Confirm Installation step", a pop "User Access Control" comes up where user will have to click on "Yes" to allow installation. Please can we add details about this pop? Some students need very clear instructions, so it can potentially reduce basic question that a trainer may receive.
![image](https://user-images.githubusercontent.com/16652407/165987909-3779b359-7422-4559-a149-a3f00d52efef.png)

**Comment by shannonlindsay** [comment]
Updated :)
