### ISSUE TITLE
Step needs to have a T icon, to paste the "Format String Expression"

### ISSUE THREAD

**Issue by strugdt** [shannonlindsay/Data-AI-Dev#8]
# Lab Name: Create calculation groups
### Step: 14

Issue Type: non-blocking

Description of issue : Please can we ensure that the expression for "Format String Expression" property provides a T icon in lab later, so it can be copied over easily by clicking.

![image](https://user-images.githubusercontent.com/16652407/165991539-f00e2f04-0b8e-4b9a-a68c-c236d1b0af0a.png)

![image](https://user-images.githubusercontent.com/77289548/164813485-54e7cc1a-7784-40d7-bda7-4627acc6345a.png)

**Comment by sherzyang** [comment]
Hi @strugdt! We just enabled copy+paste from outside the VM (eg. the instructions) to inside the VM. Hopefully this also solves for the issue.

**Comment by shannonlindsay** [comment]
I also formatted it as code so it can be copy/pasted. Now we're double safe!
