### ISSUE TITLE
DAX Code in instruction doesn't work

### ISSUE THREAD

**Issue by strugdt** [shannonlindsay/Data-AI-Dev#9]
# Lab Name: Create calculation groups
### Step: 13

Issue Type: non-blocking

Description of issue

DAX provided in instructions doesn't work, probably because line in split into 2. Code in snippet file works as it has proper new line character, and not everything is in ONE line.
![image](https://user-images.githubusercontent.com/16652407/165993662-63d7f0d5-330b-4805-a079-f6c861f26e71.png)

**Comment by shannonlindsay** [comment]
@strugdt - I struggle with this one. In the markdown, the DAX is formatted properly (and DAX formatting is important for readability), but in the instruction pane it doesn't look formatted at all. Let me look at this and think about what's best. 

For the moment I added another reminder to check out the snippets file.
